Feature: Blocks page
  Scenario: should show title, summary, and transactions
    Given I'm on page "/blocks/"
    Then I should see "Blocks" in "top title" element
    And I should see "24254 → 24235" in "sub title" element
    And I should see "Home Blocks" in "breadcrumb" element
    And I should see table "table blocks" with 20 rows starting with:
      | Id             | Height | Timestamp                 | Transactions	 | Generated by	     | Amount      | Forged   |
      |----------------|--------|---------------------------|----------------|-------------------|-------------|----------|
      | /\d{18,20}/    | 24254  | /2017\/06\/19 \d\d:33:00/ | 0              | /genesis_\d{1,3}/ | 0 LSK       | 5.0 LSK  | 
      | /\d{18,20}/    | 24253  | /2017\/06\/19 \d\d:32:50/ | 0              | /genesis_\d{1,3}/ | 0 LSK       | 5.0 LSK  | 
      | /\d{18,20}/    | 24252  | /2017\/06\/19 \d\d:32:40/ | 0              | /genesis_\d{1,3}/ | 0 LSK       | 5.0 LSK  | 
      | /\d{18,20}/    | 24251  | /2017\/06\/19 \d\d:32:30/ | 0              | /genesis_\d{1,3}/ | 0 LSK       | 5.0 LSK  | 
      | /\d{18,20}/    | 24250  | /2017\/06\/19 \d\d:18:20/ | 1              | /genesis_\d{1,3}/ | 123.45 LSK  | 5.1 LSK  | 
  
  Scenario: By clicking 2 should go to page 2 
    Given I'm on page "/blocks/"
    When I click "nav item" no. 2
    Then I should be on page "/blocks/2"

  Scenario: By clicking 1 should go to page 1 
    Given I'm on page "/blocks/"
    When I click "nav item" no. 1
    Then I should be on page "/blocks/1"

  Scenario: By clicking next button should go to page 2 
    Given I'm on page "/blocks/1"
    When I click "btn next"
    Then I should be on page "/blocks/2"

  Scenario: By clicking previous button should go to page 1 
    Given I'm on page "/blocks/2"
    When I click "btn prev"
    Then I should be on page "/blocks/1"
